/// Phase 2 route paths and GoRoute names.
abstract final class AppRoutes {
  static const login = '/login';
  static const forgotPassword = '/forgot-password';
  static const dashboard = '/dashboard';
  static const fieldToday = '/field/today';
  static const blocked = '/blocked';
  static const products = '/products';
  static const productsNew = '/products/new';
  static const productsEdit = '/products/:id/edit';
  static const productsDetail = '/products/:id';
  static const warehouses = '/warehouses';
  static const inventory = '/inventory';
  static const inventoryMovements = '/inventory/movements';
  static const inventoryTransfers = '/inventory/transfers';
  static const customers = '/customers';
  static const customersEdit = '/customers/:id/edit';
  static const customersDetail = '/customers/:id';
  static const suppliers = '/suppliers';
  static const suppliersDetail = '/suppliers/:id';
  static const accounts = '/accounts';

  static const loginName = 'login';
  static const forgotPasswordName = 'forgotPassword';
  static const dashboardName = 'dashboard';
  static const fieldTodayName = 'fieldToday';
  static const blockedName = 'blocked';
  static const productsName = 'products';
  static const productsNewName = 'productsNew';
  static const productsEditName = 'productsEdit';
  static const productsDetailName = 'productsDetail';
  static const warehousesName = 'warehouses';
  static const inventoryName = 'inventory';
  static const inventoryMovementsName = 'inventoryMovements';
  static const inventoryTransfersName = 'inventoryTransfers';
  static const customersName = 'customers';
  static const customersEditName = 'customersEdit';
  static const customersDetailName = 'customersDetail';
  static const suppliersName = 'suppliers';
  static const suppliersDetailName = 'suppliersDetail';
  static const accountsName = 'accounts';
}
